import { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { MapPin, BadgeCheck, Send, Heart, ArrowLeft } from "lucide-react";
import { getProducts, sendEnquiry } from "../services/api";
import { artisans } from "../services/data";

export default function ProductDetails(){
 const {id}=useParams(), p=getProducts().find(x=>String(x.id)===String(id))||getProducts()[0], [open,setOpen]=useState(false),[sent,setSent]=useState(false);
 const artisan=artisans.find(a=>a.name===p.artisan)||artisans[0];
 const submit=e=>{e.preventDefault();sendEnquiry({buyer:localStorage.getItem("ks_name")||"The Heritage Hotel",product:p.name,quantity:Number(e.target.quantity.value),message:e.target.message.value,location:"Delhi"});setSent(true)};
 return <div className="workspace"><Link to="/marketplace" className="back-link"><ArrowLeft size={16}/> Back to marketplace</Link><div className="detail-layout"><div className="detail-image"><img src={p.image} alt={p.name}/></div><div className="detail-copy"><span className="eyebrow">{p.craft}</span><h1>{p.name}</h1><div className="big-price">₹{p.price.toLocaleString("en-IN")} <small>/ piece</small></div><div className="detail-tags">{p.tags?.map(t=><span key={t}>#{t}</span>)}</div><p>{p.description}</p><div className="detail-specs"><div><small>Material</small><b>{p.material}</b></div><div><small>Location</small><b><MapPin size={14}/> {p.location}</b></div><div><small>Minimum order</small><b>{p.minOrder} pieces</b></div></div><div className="artisan-mini"><div className="avatar">{p.artisan?.charAt(0)||"S"}</div><div><span>ARTISAN</span><b>{p.artisan||artisan.name} <BadgeCheck size={15}/></b><small>{artisan.experience} years · ⭐ {artisan.rating}</small></div><Link to="/profile">View profile</Link></div><div className="detail-actions"><button className="btn btn-primary" onClick={()=>setOpen(true)}><Send size={17}/> Send Enquiry</button><button className="btn btn-secondary"><Heart size={17}/> Save</button></div></div></div>{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><span className="eyebrow">CONNECT WITH ARTISAN</span><h2>{sent?"Enquiry sent!":"Request a bulk order"}</h2>{sent?<><p>Your enquiry has been added to the artisan's workspace.</p><button className="btn btn-primary full" onClick={()=>setOpen(false)}>Done</button></>:<form onSubmit={submit}><label>Quantity<input name="quantity" type="number" min="1" defaultValue={p.minOrder}/></label><label>Message<textarea name="message" defaultValue={`I am interested in ordering ${p.name} for my business.`}/></label><button className="btn btn-primary full"><Send size={17}/> Send Enquiry</button></form>}</div></div>}</div>
}